### ISSUE TITLE
Alien::Build::Util::_mirror doesn't handle symlinks to directories

### ISSUE THREAD

**Issue by djerius** [PerlAlien/Alien-Build#255]
Consider the following directory structure:

```
src
├── wcslib -> wcslib-7.6
└── wcslib-7.6
    └── stamp
```

Running this command

```
_mirror( 'src', 'dest', { verbose => 1 } );
```

results in

```
dest
└── wcslib-7.6
    └── stamp
```

The symbolic link `wcslib` isn't created.  This seems to be due to the
fact that the results of `-d wcslib` and `-l wcslib` are both true.

`_mirror` first [checks if the entry is a directory](https://metacpan.org/source/PLICEASE/Alien-Build-2.38/lib/Alien/Build/Util.pm#L41), which in this case
yields true, and that code path does not result in the creation of the
symlink.  However, if `_mirror` first checks if `wcslib` is a symbolic link,
it correctly creates the link.

I don't know if simply moving the symbolic link check before the
directory check has any negative ramifications.

**Comment by plicease** [comment]
@djerius Can you try `2.39_01` out?

**Comment by djerius** [comment]
@plicease That fixed it.  Thanks!

**Comment by plicease** [comment]
:tada: Great.
