### ISSUE TITLE
RFE: issue diagnostic if Test::Alien::alien_ok hasn't been called

### ISSUE THREAD

**Issue by djerius** [PerlAlien/Alien-Build#262]
I forgot to include a call to `alien_ok` at the start of my test file, and was stumped by the fact that no compiler flags were passed to the compiler.

Through trial and error (after reading the docs multiple times and not noticing that `alien_ok` was at the start of very example), I figured it out.

However, if it's forgotten, it's not obvious what's going wrong.

After looking at the Test::Alien code, I _think_ that an empty `@aliens` array is an error.  If that's the case, perhaps checking if it's empty before using it and emitting an error saying "yo! call `alien_ok`"  might be appropriate.

**Comment by plicease** [comment]
I don't think it should fail (it could be useful to test alien-less XS), but a diag to let the user know that they haven't specified any aliens yet.

**Comment by djerius** [comment]
That would work.  Perhaps have it display a GIF of Homer Simpson slapping his forehead?

**Comment by plicease** [comment]
I think #263 should do the trick.  It adds the diagnostic to all of the testing tools, which seems sensible.

**Comment by djerius** [comment]
Thanks!
