### ISSUE TITLE
possible typo and extra whitespace in faq.pod

### ISSUE THREAD

**Issue by inphobia** [PerlAlien/Alien-Build#266]
https://github.com/PerlAlien/Alien-Build/blob/2a2d6d489af8fb846ae76f81c94173c3dc86849a/lib/Alien/Build/Manual/FAQ.pod#L322

this states "tries to use dynamic libraries instead of dynamic libraries"
i guess it must be "tries to use static libraries instead of dynamic libraries"?

also, there are a few strange whitespaces here:
https://github.com/PerlAlien/Alien-Build/blob/2a2d6d489af8fb846ae76f81c94173c3dc86849a/lib/Alien/Build/Manual/FAQ.pod#L311

namely here:
`Alien/XS/ Mod0/Mod0.so` between XS & Mod0
`/opt /perl/5.30.1` between opt & perl

i don't think those are intended, but haven't figured out if it's a typo in faq.pod or if this is the actual output that was copied (in other words, don't know if it needs to be fixed in faq.pod or whatever module generated this output).

**Comment by plicease** [comment]
Thanks for reporting this.  Should be addressed in #267
