### ISSUE TITLE
Cross compiling

### ISSUE THREAD

**Issue by m-fonseca** [PerlAlien/Alien-Build#271]
Hello,

I didn't see any mention of cross compiling anywhere in the Alien-Build docs or issues.  Is there any guidance/info on cross compiling modules uising Alien-Build  (specifically I'm trying to cross compile Google-ProtocolBuffers-Dynamic, which uses Alien::uPB)?

Thank you!

**Comment by plicease** [comment]
AB like Perl doesn't really support cross-compiling out of the box.  One way it might work would be if the Alien used `pkg-config` for probe and do a system install.  Some Aliens require building a test program and running that natively which will break cross-compiling obviously.  I don't have any experience using `Alien::uPB` myself, but just glancing over the code, it does not look like it would be cross-compile friendly as is.  I am happy to add some hooks to make this easier in AB core, but at least some work would be needed in `Alien::uPB` and any other aliens that would need to be cross-compiled.
