### ISSUE TITLE
Avoid installing Alien::Build if user already has installed the external library?

### ISSUE THREAD

**Issue by hakonhagland** [PerlAlien/Alien-Build#279]
I guess this is not possible, but I just wanted to check. For example, [Math::GSL](https://metacpan.org/pod/Math::GSL) uses [Alien::GSL](https://metacpan.org/pod/Alien::GSL) in its [configure_requires in Build.PL](https://metacpan.org/release/HAKONH/Math-GSL-0.42/source/Build.PL#L138), when running `./Build dist` this is written to [META.json](https://metacpan.org/release/HAKONH/Math-GSL-0.42/source/META.json) such that install tools like `cpanm` can install the prerequisite `Alien::GSL` before installing `Math::GSL`. However, the user may already have installed GNU GSL from either [source](https://www.gnu.org/software/gsl/) or from a package manager on his OS, for example on Ubuntu by running `sudo apt-get install libgsl-dev`. In this case the install tool (e.g. `cpanm`) will still try to install `Alien::GSL` and its dependencies (`Alien::Build`, ...) even if they are not needed. Is it possible to avoid this ?

**Comment by Grinnz** [comment]
Not easily, because Alien::Build is the mechanism by which it can determine whether the appropriate library is available (this information is read from the alienfile, etc).

**Comment by plicease** [comment]
It is possible, `FFI::Platypus` does this, by bundling `Alien::Base::Wrapper` (ABW), which allows it to compute the compiler/linker flags after the configure stage if it needs to fallback on an Alien install.  ABW comes with Alien-Build, but it was intentionally written with no non-core prereqs as of Perl 5.8 for use in exactly such a scenario.

https://github.com/PerlFFI/FFI-Platypus/blob/main/inc/mymm.pl#L49-L99

Platypus actually uses multiple detection strategies before falling back on `Alien::FFI` (and uses `Alien::FFI` if it happens to already be installed), so what you would need to do might be less complicated than this, but there are still a lot of pitfalls and sharp edges, and obviously duplicated detection code.  For that reason, I don't recommend it unless there is a compelling reason.  The main rationale for doing this in Platypus is to in some cases allow Alien plugins to rely on FFI potentially, though at the moment I don't think there is an example where we do this.
