### ISSUE TITLE
Probe::CBuilder: die calls use $@ after it has been reset by log calls

### ISSUE THREAD

**Issue by shawnlaffan** [PerlAlien/Alien-Build#296]
Should lines 160 and 174 be ```die $error```?

https://github.com/PerlAlien/Alien-Build/blob/8153045a56c383af393c02b1ded693048652ff7e/lib/Alien/Build/Plugin/Probe/CBuilder.pm#L156-L161

https://github.com/PerlAlien/Alien-Build/blob/8153045a56c383af393c02b1ded693048652ff7e/lib/Alien/Build/Plugin/Probe/CBuilder.pm#L170-L175

**Comment by zmughal** [comment]
> Should lines 160 and 174 be `die $error`?

Yeah, that makes sense. PR?

**Comment by plicease** [comment]
Yup this was definitely a mistake on my part thanks for reporting.

**Comment by plicease** [comment]
Fix is on its way to CPAN as 2.47.
