### ISSUE TITLE
Access to the current interpolation engine; documentation of standard property hierarchies

### ISSUE THREAD

**Issue by djerius** [PerlAlien/Alien-Build#312]
I'd like to use the interpolation engine in some custom patch code, e.g.

```
patch sub ($build) {
    my $patch = $build->meta->interpolator->interpolate( '%{.install.patch}/cfitsio-%{.runtime.version}.patch' ); 
    ...
};
```
But I'm getting the following error:

`No property .install.patch is defined`

which implies that that the interpolator hasn't been properly initialized yet.  Attempts to find `.patch` in some other property hierarchy have failed.

It's unclear when the interpolation engine is populated with which properties.  Is that something that can be documented?

As an add-on, it would be helpful to know what the property hierarchies are.  They are mentioned in the documentation in examples, but a reference section which laid out the hierarchies in one place would be very useful.

**EDIT**
Well, digging into the Alien code, I came up with this:
`$build->meta->interpolator->interpolate( $patchfile, $build->_command_prop  );`
but that uses two(!) undocumented things; the second argument to `Alien::Build::Interpolate::interpolate`, and the `Alien::Build::_command_prop` method.

**Comment by plicease** [comment]
For `.install.patch` specifically, this property is set at the start if the `patch` directory exists.  I believe the logic is actually in `Alien::Build::MM` (or `::MB`) so it gets set quite early.  I've added some notes in the property documentation on `Alien::Build` for exactly this.  I've also added some other notes about when specific properties are set.  #327

The properties hierarchy is documented here:
https://metacpan.org/pod/Alien::Build#PROPERTIES

**Comment by plicease** [comment]
Ah okay I think I understand a little better now.  The fail isn't because `.install.patch` isn't set, it is because the interpolator doesn't have the property list from `Alien::Build`.  This is probably something that we can fix.  In the near term this is what you can do:

```perl
patch sub ($build) {
    my $patch = $build->meta->interpolator->interpolate( '%{.install.patch}/cfitsio-%{.runtime.version}.patch' ); 
    ...
};
```

**Comment by plicease** [comment]
I think having access to what the `$build->system` method does would be useful though, let me think of a good interface.

**Comment by plicease** [comment]
#337 should address this.

**Comment by djerius** [comment]
Thanks!
