### ISSUE TITLE
Doc bug: example/README gives incorrect command syntax

### ISSUE THREAD

**Issue by jimav** [PerlAlien/Alien-Build#399]
I'm an Alien newbie, trying out the examples in the `example/README` .  However those examples fail with 
```
unable to read .../example/alienfile
```
because the commands shown omit the `--file` option before the alienfile path.   For example, the second example given in example/README is
```
% af install --type=share --prefix=/tmp/foo xz.alienfile
```
but should be
```
% af install xz.alienfile --type=share --prefix=/tmp/foo --file xz.alienfile
```
FWIW I'm using `af` command version 0.18

**Comment by plicease** [comment]
Thank you for reporting this, #400 should address it!
