### ISSUE TITLE
arm64-freebsd not detected

### ISSUE THREAD

**Issue by eserte** [PerlAlien/Alien-Build#411]
Perls on arm freebsd 14 systems may report as the archname 'arm64-freebsd' (which seems to be the case for the system perl) or 'aarch64-freebsd' (for self-compiled perls). For the former this means that the arch is not detected by Alien::Build:

```
$ perl -Mblib t/alien_build_plugin_core_setup.t
...
ok 3 - CPU arch {
    # Architecture detection: Unknown archname 'arm64-freebsd'. at /home/cpansand/.cpan/build/2024052320/Alien-Build-2.80-0/blib/lib/Alien/Build/Plugin/Core/Setup.pm line 247.
    ok 1 - alienfile compiles
    ok 2 - has a CPU arch
    # CPU arch:
    # ---
    # name: unknown
    1..2
}
```

**Comment by plicease** [comment]
Thank you for reporting this, it is very helpful since it won't fail AB testing, but some downstream Aliens might.  Can you try `2.82_01` and let me know?  I can then cut a production release if it looks good.

**Comment by eserte** [comment]
Looks good with 2.82_01:
```
$ perl -Mblib t/alien_build_plugin_core_setup.t

...
ok 3 - CPU arch {
    ok 1 - alienfile compiles
    ok 2 - has a CPU arch
    # CPU arch:
    # $VAR1 = {
    #           'name' => 'aarch64'
    #         };
    1..2
}
```

**Comment by plicease** [comment]
👍🏻 prod version on its way to CPAN now.
