### ISSUE TITLE
add methods for is_share_install and is_system_install

### ISSUE THREAD

**Issue by shawnlaffan** [PerlAlien/Alien-Build#418]
The current code to check if an alien is a share or system install uses string comparison or arguments, e.g. `Alien::somepackage->install_type eq 'system'` or `Alien::somepackage->install_type('system')`.  

This has the risk of typos returning incorrect results.  For example comparing against `systen` will return false on both share and system installs.  

It would be useful to have methods to check the install that take no arguments.  That way any typos are raised at compile time.  

The simplest implementation would be wrappers around `install_type`.  

If this seems like a decent idea then I'll work up a PR.

**Comment by plicease** [comment]
Yeah that would be great to add.  The way it is is for historical reasons.  We should also deprecate the old methods in the documentation.  We won't be able to remove them, but we should make it clear to use the new ones.

**Comment by shawnlaffan** [comment]
Fixed by #420
