### ISSUE TITLE
Improve plugin documentation.

### ISSUE THREAD

**Issue by plicease** [PerlAlien/Alien-Build#48]
What exists is somewhat incomplete in parts, out of date in others and there is no tutorial.

Inspiration and lessons learned can be drawn from #42 

Two types of plugins should be addressed in said documentation:

 - process plugins, (build, probe, gather, etc) which are used directly in an alienfile as part of the recipe
 - environment plugins (cache, URL rewriters, etc) which are used by end users to adjust behaviors (Alien::Build::Plugin::Fetch::Cache as an example).

I am assigning this to me, but anyone else should feel welcome to make comments or PRs to improve this.

**Comment by shawnlaffan** [comment]
Some possible typos are near the end of Alien::Build::Manual::PluginAuthor.  I have not delved into the code to check for certain.  

I assume the example for the gather_share hook should use a sub called ```gather_share_hook => ```?  

Currently it is: 

```perl
$meta->register_hook( register_hook => sub {
  my($build) = @_;
  ... 
});
```

The gather_ffi example uses register_ffi, should it be ```gather_ffi => sub```?

**Comment by plicease** [comment]
Closing this in favor of #313, which already has a lot more detail.  The specific suggestions mentioned in this issue have already been addressed.
